/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export declare namespace OptionMarketWrapperWithSwaps {
  export type OptionMarketContractsStruct = {
    quoteAsset: PromiseOrValue<string>;
    baseAsset: PromiseOrValue<string>;
    optionToken: PromiseOrValue<string>;
    liquidityPool: PromiseOrValue<string>;
    liquidityToken: PromiseOrValue<string>;
  };

  export type OptionMarketContractsStructOutput = [
    string,
    string,
    string,
    string,
    string
  ] & {
    quoteAsset: string;
    baseAsset: string;
    optionToken: string;
    liquidityPool: string;
    liquidityToken: string;
  };

  export type OptionPositionParamsStruct = {
    optionMarket: PromiseOrValue<string>;
    strikeId: PromiseOrValue<BigNumberish>;
    positionId: PromiseOrValue<BigNumberish>;
    iterations: PromiseOrValue<BigNumberish>;
    setCollateralTo: PromiseOrValue<BigNumberish>;
    currentCollateral: PromiseOrValue<BigNumberish>;
    optionType: PromiseOrValue<BigNumberish>;
    amount: PromiseOrValue<BigNumberish>;
    minCost: PromiseOrValue<BigNumberish>;
    maxCost: PromiseOrValue<BigNumberish>;
    inputAmount: PromiseOrValue<BigNumberish>;
    inputAsset: PromiseOrValue<string>;
  };

  export type OptionPositionParamsStructOutput = [
    string,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    number,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    string
  ] & {
    optionMarket: string;
    strikeId: BigNumber;
    positionId: BigNumber;
    iterations: BigNumber;
    setCollateralTo: BigNumber;
    currentCollateral: BigNumber;
    optionType: number;
    amount: BigNumber;
    minCost: BigNumber;
    maxCost: BigNumber;
    inputAmount: BigNumber;
    inputAsset: string;
  };

  export type ReturnDetailsStruct = {
    market: PromiseOrValue<string>;
    positionId: PromiseOrValue<BigNumberish>;
    owner: PromiseOrValue<string>;
    amount: PromiseOrValue<BigNumberish>;
    totalCost: PromiseOrValue<BigNumberish>;
    totalFee: PromiseOrValue<BigNumberish>;
    swapFee: PromiseOrValue<BigNumberish>;
    token: PromiseOrValue<string>;
  };

  export type ReturnDetailsStructOutput = [
    string,
    BigNumber,
    string,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    string
  ] & {
    market: string;
    positionId: BigNumber;
    owner: string;
    amount: BigNumber;
    totalCost: BigNumber;
    totalFee: BigNumber;
    swapFee: BigNumber;
    token: string;
  };

  export type StableAssetViewStruct = {
    id: PromiseOrValue<BigNumberish>;
    token: PromiseOrValue<string>;
    decimals: PromiseOrValue<BigNumberish>;
    symbol: PromiseOrValue<string>;
    balance: PromiseOrValue<BigNumberish>;
    allowance: PromiseOrValue<BigNumberish>;
  };

  export type StableAssetViewStructOutput = [
    number,
    string,
    number,
    string,
    BigNumber,
    BigNumber
  ] & {
    id: number;
    token: string;
    decimals: number;
    symbol: string;
    balance: BigNumber;
    allowance: BigNumber;
  };

  export type MarketAssetViewStruct = {
    id: PromiseOrValue<BigNumberish>;
    market: PromiseOrValue<string>;
    token: PromiseOrValue<string>;
    decimals: PromiseOrValue<BigNumberish>;
    symbol: PromiseOrValue<string>;
    balance: PromiseOrValue<BigNumberish>;
    allowance: PromiseOrValue<BigNumberish>;
    isApprovedForAll: PromiseOrValue<boolean>;
  };

  export type MarketAssetViewStructOutput = [
    number,
    string,
    string,
    number,
    string,
    BigNumber,
    BigNumber,
    boolean
  ] & {
    id: number;
    market: string;
    token: string;
    decimals: number;
    symbol: string;
    balance: BigNumber;
    allowance: BigNumber;
    isApprovedForAll: boolean;
  };

  export type LiquidityBalanceAndAllowanceStruct = {
    token: PromiseOrValue<string>;
    balance: PromiseOrValue<BigNumberish>;
    allowance: PromiseOrValue<BigNumberish>;
  };

  export type LiquidityBalanceAndAllowanceStructOutput = [
    string,
    BigNumber,
    BigNumber
  ] & { token: string; balance: BigNumber; allowance: BigNumber };
}

export interface OptionMarketWrapperInterface extends utils.Interface {
  functions: {
    "acceptOwnership()": FunctionFragment;
    "addCurveStable(address,uint8)": FunctionFragment;
    "addLong(uint256)": FunctionFragment;
    "addMarket(address,uint8,(address,address,address,address,address))": FunctionFragment;
    "addShort(uint256)": FunctionFragment;
    "closeLong(uint256)": FunctionFragment;
    "closePosition((address,uint256,uint256,uint256,uint256,uint256,uint8,uint256,uint256,uint256,uint256,address))": FunctionFragment;
    "closeShort(uint256)": FunctionFragment;
    "curveSwap()": FunctionFragment;
    "ercIds(uint256)": FunctionFragment;
    "forceClosePosition((address,uint256,uint256,uint256,uint256,uint256,uint8,uint256,uint256,uint256,uint256,address))": FunctionFragment;
    "getBalancesAndAllowances(address)": FunctionFragment;
    "getMarketAndErcIds()": FunctionFragment;
    "idToERC(uint8)": FunctionFragment;
    "idToMarket(uint8)": FunctionFragment;
    "marketContracts(address)": FunctionFragment;
    "marketIds(uint256)": FunctionFragment;
    "minReturnPercent()": FunctionFragment;
    "nominateNewOwner(address)": FunctionFragment;
    "nominatedOwner()": FunctionFragment;
    "openLong(uint256)": FunctionFragment;
    "openPosition((address,uint256,uint256,uint256,uint256,uint256,uint8,uint256,uint256,uint256,uint256,address))": FunctionFragment;
    "openShort(uint256)": FunctionFragment;
    "owner()": FunctionFragment;
    "quoteCurveSwap(address,address,uint256)": FunctionFragment;
    "reduceLong(uint256)": FunctionFragment;
    "reduceShort(uint256)": FunctionFragment;
    "removeCurveStable(uint8)": FunctionFragment;
    "removeMarket(uint8)": FunctionFragment;
    "synthetixAdapter()": FunctionFragment;
    "tradingRewards()": FunctionFragment;
    "updateContractParams(address,address,address,uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "acceptOwnership"
      | "addCurveStable"
      | "addLong"
      | "addMarket"
      | "addShort"
      | "closeLong"
      | "closePosition"
      | "closeShort"
      | "curveSwap"
      | "ercIds"
      | "forceClosePosition"
      | "getBalancesAndAllowances"
      | "getMarketAndErcIds"
      | "idToERC"
      | "idToMarket"
      | "marketContracts"
      | "marketIds"
      | "minReturnPercent"
      | "nominateNewOwner"
      | "nominatedOwner"
      | "openLong"
      | "openPosition"
      | "openShort"
      | "owner"
      | "quoteCurveSwap"
      | "reduceLong"
      | "reduceShort"
      | "removeCurveStable"
      | "removeMarket"
      | "synthetixAdapter"
      | "tradingRewards"
      | "updateContractParams"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "acceptOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addCurveStable",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "addLong",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "addMarket",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      OptionMarketWrapperWithSwaps.OptionMarketContractsStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "addShort",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "closeLong",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "closePosition",
    values: [OptionMarketWrapperWithSwaps.OptionPositionParamsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "closeShort",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: "curveSwap", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ercIds",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "forceClosePosition",
    values: [OptionMarketWrapperWithSwaps.OptionPositionParamsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "getBalancesAndAllowances",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getMarketAndErcIds",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "idToERC",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "idToMarket",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "marketContracts",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "marketIds",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "minReturnPercent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nominateNewOwner",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "nominatedOwner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "openLong",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "openPosition",
    values: [OptionMarketWrapperWithSwaps.OptionPositionParamsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "openShort",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "quoteCurveSwap",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "reduceLong",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "reduceShort",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "removeCurveStable",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "removeMarket",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "synthetixAdapter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "tradingRewards",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateContractParams",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addCurveStable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addLong", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "addMarket", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "addShort", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "closeLong", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "closePosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "closeShort", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "curveSwap", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ercIds", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "forceClosePosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBalancesAndAllowances",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMarketAndErcIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "idToERC", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "idToMarket", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "marketContracts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "marketIds", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "minReturnPercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nominateNewOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nominatedOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "openLong", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "openPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "openShort", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "quoteCurveSwap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "reduceLong", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "reduceShort",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeCurveStable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "synthetixAdapter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tradingRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateContractParams",
    data: BytesLike
  ): Result;

  events: {
    "OwnerChanged(address,address)": EventFragment;
    "OwnerNominated(address)": EventFragment;
    "PositionTraded(bool,bool,address,uint256,address,uint256,uint256,uint256,int256,address)": EventFragment;
    "SetCollateralTo(uint256)": EventFragment;
    "WrapperParamsUpdated(address,address,address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OwnerChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnerNominated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PositionTraded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetCollateralTo"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "WrapperParamsUpdated"): EventFragment;
}

export interface OwnerChangedEventObject {
  oldOwner: string;
  newOwner: string;
}
export type OwnerChangedEvent = TypedEvent<
  [string, string],
  OwnerChangedEventObject
>;

export type OwnerChangedEventFilter = TypedEventFilter<OwnerChangedEvent>;

export interface OwnerNominatedEventObject {
  newOwner: string;
}
export type OwnerNominatedEvent = TypedEvent<
  [string],
  OwnerNominatedEventObject
>;

export type OwnerNominatedEventFilter = TypedEventFilter<OwnerNominatedEvent>;

export interface PositionTradedEventObject {
  isOpen: boolean;
  isLong: boolean;
  market: string;
  positionId: BigNumber;
  owner: string;
  amount: BigNumber;
  totalCost: BigNumber;
  totalFee: BigNumber;
  swapFee: BigNumber;
  token: string;
}
export type PositionTradedEvent = TypedEvent<
  [
    boolean,
    boolean,
    string,
    BigNumber,
    string,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    string
  ],
  PositionTradedEventObject
>;

export type PositionTradedEventFilter = TypedEventFilter<PositionTradedEvent>;

export interface SetCollateralToEventObject {
  newCollateral: BigNumber;
}
export type SetCollateralToEvent = TypedEvent<
  [BigNumber],
  SetCollateralToEventObject
>;

export type SetCollateralToEventFilter = TypedEventFilter<SetCollateralToEvent>;

export interface WrapperParamsUpdatedEventObject {
  curveSwap: string;
  synthetixAdapter: string;
  tradingRewards: string;
  minReturnPercent: BigNumber;
}
export type WrapperParamsUpdatedEvent = TypedEvent<
  [string, string, string, BigNumber],
  WrapperParamsUpdatedEventObject
>;

export type WrapperParamsUpdatedEventFilter =
  TypedEventFilter<WrapperParamsUpdatedEvent>;

export interface OptionMarketWrapper extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: OptionMarketWrapperInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    acceptOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    addCurveStable(
      token: PromiseOrValue<string>,
      id: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    addLong(
      params: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    addMarket(
      optionMarket: PromiseOrValue<string>,
      id: PromiseOrValue<BigNumberish>,
      _marketContracts: OptionMarketWrapperWithSwaps.OptionMarketContractsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    addShort(
      params: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    closeLong(
      params: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    closePosition(
      params: OptionMarketWrapperWithSwaps.OptionPositionParamsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    closeShort(
      params: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    curveSwap(overrides?: CallOverrides): Promise<[string]>;

    ercIds(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[number]>;

    forceClosePosition(
      params: OptionMarketWrapperWithSwaps.OptionPositionParamsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getBalancesAndAllowances(
      owner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [
        OptionMarketWrapperWithSwaps.StableAssetViewStructOutput[],
        OptionMarketWrapperWithSwaps.MarketAssetViewStructOutput[],
        OptionMarketWrapperWithSwaps.LiquidityBalanceAndAllowanceStructOutput[]
      ]
    >;

    getMarketAndErcIds(
      overrides?: CallOverrides
    ): Promise<[number[], number[]]>;

    idToERC(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    idToMarket(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    marketContracts(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [string, string, string, string, string] & {
        quoteAsset: string;
        baseAsset: string;
        optionToken: string;
        liquidityPool: string;
        liquidityToken: string;
      }
    >;

    marketIds(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[number]>;

    minReturnPercent(overrides?: CallOverrides): Promise<[BigNumber]>;

    nominateNewOwner(
      _owner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    nominatedOwner(overrides?: CallOverrides): Promise<[string]>;

    openLong(
      params: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    openPosition(
      params: OptionMarketWrapperWithSwaps.OptionPositionParamsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    openShort(
      params: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    quoteCurveSwap(
      fromToken: PromiseOrValue<string>,
      toToken: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string, BigNumber] & { pool: string; amountOut: BigNumber }>;

    reduceLong(
      params: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    reduceShort(
      params: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    removeCurveStable(
      id: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    removeMarket(
      id: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    synthetixAdapter(overrides?: CallOverrides): Promise<[string]>;

    tradingRewards(overrides?: CallOverrides): Promise<[string]>;

    updateContractParams(
      _curveSwap: PromiseOrValue<string>,
      _synthetixAdapter: PromiseOrValue<string>,
      _tradingRewards: PromiseOrValue<string>,
      _minReturnPercent: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  acceptOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  addCurveStable(
    token: PromiseOrValue<string>,
    id: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  addLong(
    params: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  addMarket(
    optionMarket: PromiseOrValue<string>,
    id: PromiseOrValue<BigNumberish>,
    _marketContracts: OptionMarketWrapperWithSwaps.OptionMarketContractsStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  addShort(
    params: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  closeLong(
    params: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  closePosition(
    params: OptionMarketWrapperWithSwaps.OptionPositionParamsStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  closeShort(
    params: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  curveSwap(overrides?: CallOverrides): Promise<string>;

  ercIds(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<number>;

  forceClosePosition(
    params: OptionMarketWrapperWithSwaps.OptionPositionParamsStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getBalancesAndAllowances(
    owner: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<
    [
      OptionMarketWrapperWithSwaps.StableAssetViewStructOutput[],
      OptionMarketWrapperWithSwaps.MarketAssetViewStructOutput[],
      OptionMarketWrapperWithSwaps.LiquidityBalanceAndAllowanceStructOutput[]
    ]
  >;

  getMarketAndErcIds(overrides?: CallOverrides): Promise<[number[], number[]]>;

  idToERC(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  idToMarket(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  marketContracts(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<
    [string, string, string, string, string] & {
      quoteAsset: string;
      baseAsset: string;
      optionToken: string;
      liquidityPool: string;
      liquidityToken: string;
    }
  >;

  marketIds(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<number>;

  minReturnPercent(overrides?: CallOverrides): Promise<BigNumber>;

  nominateNewOwner(
    _owner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  nominatedOwner(overrides?: CallOverrides): Promise<string>;

  openLong(
    params: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  openPosition(
    params: OptionMarketWrapperWithSwaps.OptionPositionParamsStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  openShort(
    params: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  owner(overrides?: CallOverrides): Promise<string>;

  quoteCurveSwap(
    fromToken: PromiseOrValue<string>,
    toToken: PromiseOrValue<string>,
    amountIn: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<[string, BigNumber] & { pool: string; amountOut: BigNumber }>;

  reduceLong(
    params: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  reduceShort(
    params: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  removeCurveStable(
    id: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  removeMarket(
    id: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  synthetixAdapter(overrides?: CallOverrides): Promise<string>;

  tradingRewards(overrides?: CallOverrides): Promise<string>;

  updateContractParams(
    _curveSwap: PromiseOrValue<string>,
    _synthetixAdapter: PromiseOrValue<string>,
    _tradingRewards: PromiseOrValue<string>,
    _minReturnPercent: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    acceptOwnership(overrides?: CallOverrides): Promise<void>;

    addCurveStable(
      token: PromiseOrValue<string>,
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    addLong(
      params: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    addMarket(
      optionMarket: PromiseOrValue<string>,
      id: PromiseOrValue<BigNumberish>,
      _marketContracts: OptionMarketWrapperWithSwaps.OptionMarketContractsStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    addShort(
      params: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    closeLong(
      params: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    closePosition(
      params: OptionMarketWrapperWithSwaps.OptionPositionParamsStruct,
      overrides?: CallOverrides
    ): Promise<OptionMarketWrapperWithSwaps.ReturnDetailsStructOutput>;

    closeShort(
      params: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    curveSwap(overrides?: CallOverrides): Promise<string>;

    ercIds(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<number>;

    forceClosePosition(
      params: OptionMarketWrapperWithSwaps.OptionPositionParamsStruct,
      overrides?: CallOverrides
    ): Promise<OptionMarketWrapperWithSwaps.ReturnDetailsStructOutput>;

    getBalancesAndAllowances(
      owner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [
        OptionMarketWrapperWithSwaps.StableAssetViewStructOutput[],
        OptionMarketWrapperWithSwaps.MarketAssetViewStructOutput[],
        OptionMarketWrapperWithSwaps.LiquidityBalanceAndAllowanceStructOutput[]
      ]
    >;

    getMarketAndErcIds(
      overrides?: CallOverrides
    ): Promise<[number[], number[]]>;

    idToERC(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    idToMarket(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    marketContracts(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [string, string, string, string, string] & {
        quoteAsset: string;
        baseAsset: string;
        optionToken: string;
        liquidityPool: string;
        liquidityToken: string;
      }
    >;

    marketIds(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<number>;

    minReturnPercent(overrides?: CallOverrides): Promise<BigNumber>;

    nominateNewOwner(
      _owner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    nominatedOwner(overrides?: CallOverrides): Promise<string>;

    openLong(
      params: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    openPosition(
      params: OptionMarketWrapperWithSwaps.OptionPositionParamsStruct,
      overrides?: CallOverrides
    ): Promise<OptionMarketWrapperWithSwaps.ReturnDetailsStructOutput>;

    openShort(
      params: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<string>;

    quoteCurveSwap(
      fromToken: PromiseOrValue<string>,
      toToken: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string, BigNumber] & { pool: string; amountOut: BigNumber }>;

    reduceLong(
      params: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    reduceShort(
      params: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    removeCurveStable(
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    removeMarket(
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    synthetixAdapter(overrides?: CallOverrides): Promise<string>;

    tradingRewards(overrides?: CallOverrides): Promise<string>;

    updateContractParams(
      _curveSwap: PromiseOrValue<string>,
      _synthetixAdapter: PromiseOrValue<string>,
      _tradingRewards: PromiseOrValue<string>,
      _minReturnPercent: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "OwnerChanged(address,address)"(
      oldOwner?: null,
      newOwner?: null
    ): OwnerChangedEventFilter;
    OwnerChanged(oldOwner?: null, newOwner?: null): OwnerChangedEventFilter;

    "OwnerNominated(address)"(newOwner?: null): OwnerNominatedEventFilter;
    OwnerNominated(newOwner?: null): OwnerNominatedEventFilter;

    "PositionTraded(bool,bool,address,uint256,address,uint256,uint256,uint256,int256,address)"(
      isOpen?: null,
      isLong?: null,
      market?: PromiseOrValue<string> | null,
      positionId?: PromiseOrValue<BigNumberish> | null,
      owner?: PromiseOrValue<string> | null,
      amount?: null,
      totalCost?: null,
      totalFee?: null,
      swapFee?: null,
      token?: null
    ): PositionTradedEventFilter;
    PositionTraded(
      isOpen?: null,
      isLong?: null,
      market?: PromiseOrValue<string> | null,
      positionId?: PromiseOrValue<BigNumberish> | null,
      owner?: PromiseOrValue<string> | null,
      amount?: null,
      totalCost?: null,
      totalFee?: null,
      swapFee?: null,
      token?: null
    ): PositionTradedEventFilter;

    "SetCollateralTo(uint256)"(
      newCollateral?: null
    ): SetCollateralToEventFilter;
    SetCollateralTo(newCollateral?: null): SetCollateralToEventFilter;

    "WrapperParamsUpdated(address,address,address,uint256)"(
      curveSwap?: null,
      synthetixAdapter?: null,
      tradingRewards?: null,
      minReturnPercent?: null
    ): WrapperParamsUpdatedEventFilter;
    WrapperParamsUpdated(
      curveSwap?: null,
      synthetixAdapter?: null,
      tradingRewards?: null,
      minReturnPercent?: null
    ): WrapperParamsUpdatedEventFilter;
  };

  estimateGas: {
    acceptOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    addCurveStable(
      token: PromiseOrValue<string>,
      id: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    addLong(
      params: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    addMarket(
      optionMarket: PromiseOrValue<string>,
      id: PromiseOrValue<BigNumberish>,
      _marketContracts: OptionMarketWrapperWithSwaps.OptionMarketContractsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    addShort(
      params: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    closeLong(
      params: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    closePosition(
      params: OptionMarketWrapperWithSwaps.OptionPositionParamsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    closeShort(
      params: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    curveSwap(overrides?: CallOverrides): Promise<BigNumber>;

    ercIds(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    forceClosePosition(
      params: OptionMarketWrapperWithSwaps.OptionPositionParamsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getBalancesAndAllowances(
      owner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getMarketAndErcIds(overrides?: CallOverrides): Promise<BigNumber>;

    idToERC(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    idToMarket(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    marketContracts(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    marketIds(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    minReturnPercent(overrides?: CallOverrides): Promise<BigNumber>;

    nominateNewOwner(
      _owner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    nominatedOwner(overrides?: CallOverrides): Promise<BigNumber>;

    openLong(
      params: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    openPosition(
      params: OptionMarketWrapperWithSwaps.OptionPositionParamsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    openShort(
      params: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    quoteCurveSwap(
      fromToken: PromiseOrValue<string>,
      toToken: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    reduceLong(
      params: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    reduceShort(
      params: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    removeCurveStable(
      id: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    removeMarket(
      id: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    synthetixAdapter(overrides?: CallOverrides): Promise<BigNumber>;

    tradingRewards(overrides?: CallOverrides): Promise<BigNumber>;

    updateContractParams(
      _curveSwap: PromiseOrValue<string>,
      _synthetixAdapter: PromiseOrValue<string>,
      _tradingRewards: PromiseOrValue<string>,
      _minReturnPercent: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    acceptOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    addCurveStable(
      token: PromiseOrValue<string>,
      id: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    addLong(
      params: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    addMarket(
      optionMarket: PromiseOrValue<string>,
      id: PromiseOrValue<BigNumberish>,
      _marketContracts: OptionMarketWrapperWithSwaps.OptionMarketContractsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    addShort(
      params: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    closeLong(
      params: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    closePosition(
      params: OptionMarketWrapperWithSwaps.OptionPositionParamsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    closeShort(
      params: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    curveSwap(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    ercIds(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    forceClosePosition(
      params: OptionMarketWrapperWithSwaps.OptionPositionParamsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getBalancesAndAllowances(
      owner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getMarketAndErcIds(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    idToERC(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    idToMarket(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    marketContracts(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    marketIds(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    minReturnPercent(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    nominateNewOwner(
      _owner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    nominatedOwner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    openLong(
      params: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    openPosition(
      params: OptionMarketWrapperWithSwaps.OptionPositionParamsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    openShort(
      params: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    quoteCurveSwap(
      fromToken: PromiseOrValue<string>,
      toToken: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    reduceLong(
      params: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    reduceShort(
      params: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    removeCurveStable(
      id: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    removeMarket(
      id: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    synthetixAdapter(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    tradingRewards(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    updateContractParams(
      _curveSwap: PromiseOrValue<string>,
      _synthetixAdapter: PromiseOrValue<string>,
      _tradingRewards: PromiseOrValue<string>,
      _minReturnPercent: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
